// Generated by tools/import_content_workbook.py. Do not edit by hand.
package com.wildlife.feasibility

internal object GeneratedProgressionConfig {
    const val VERSION = "progression-0.2-regional-experimental"
    val confirmedObservationXp = 10
    val firstSpeciesXp = 500
    val researchGradeXp = 50
    val researchGradeEnabled = true
    val regionalDiscoveryXp = 100
    val regionalLegendXp = 1000
    val regionalEssentialsXp = 1500
    val regionalIconsXp = 3000
    val identificationGivenXp = 25
    val identificationGivenEnabled = false
    val anomalyConfirmedXp = 250
    val anomalyConfirmedEnabled = false
    val rarityXp = mapOf(
        EncounterRarity.COMMON to 0,
        EncounterRarity.UNCOMMON to 50,
        EncounterRarity.RARE to 150,
        EncounterRarity.VERY_RARE to 300,
        EncounterRarity.UNKNOWN to 0,
    )
    val repeatObservationXp = listOf(10, 5, 5)
    val levels = listOf(
        ProgressionLevel("tourist", "Tourist", 0),
        ProgressionLevel("explorer", "Explorer", 500),
        ProgressionLevel("naturalist", "Naturalist", 2500),
        ProgressionLevel("tracker", "Tracker", 7500),
        ProgressionLevel("field_ranger", "Field Ranger", 20000),
        ProgressionLevel("master_ranger", "Master Ranger", 50000),
        ProgressionLevel("legendary_ranger", "Legendary Ranger", 100000),
    )
}
